server:
  port: 8070
spring:
  application:
    name: service-provider
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/**/api/**        # 断言，路径相匹配的进行路由
ribbon:
  eager-load:
    enabled: false
